name: TheBusyBot

on:
  schedule:
  - cron: '*/15 * * * *'

jobs:
  runner:

    runs-on: ubuntu-latest

    steps:
    - name: Checking out Repository
      uses: actions/checkout@v1
      with:
        ref: gh-pages
    - name: Setting up Java 11
      uses: actions/setup-java@v1.4.3
      with:
        java-version: '11'
        java-package: jdk
        architecture: x64
    - name: Setting up node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Installing dependencies
      run: npm install
    - name: Setting up remote
      run: sh src/setup.sh
      env:
        LOGIN_EMAIL: ${{ secrets.LOGIN_EMAIL }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    - name: Executing program
      run: node src/single-run.js
      env:
        JSON_CONFIG: ${{ secrets.JSON_CONFIG }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
