name: System Test

on:
  push:
    branches:
    - gh-pages

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checking out Repository
      uses: actions/checkout@v2.3.4
      with:
        ref: gh-pages
    - name: Setup Java JDK 11
      uses: actions/setup-java@v2.2.0
      with:
        distribution: 'adopt'
        java-version: '11'
        java-package: jdk
        architecture: x64
    - name: Setting up node.js
      uses: actions/setup-node@v2.4.0
      with:
        node-version: '12'
    - name: Installing dependencies
      run: npm install
    - name: Executing Tests
      run: npm run test
      env:
        JSON_CONFIG: ${{ secrets.JSON_CONFIG }}
